name: "git-operations"
version: "1.0.0"
description: "Standard git operations (commit, push, PR creation)"

# Trigger condition
trigger:
  condition: "true"

# Context requirements
context:
  repo_required: true
  branch_strategy: "inherit"

# Input schema
# inputs:
#   repo: string (required)
#   branch: string (required)
#   operation: string (required) - commit | push | create_pr | commit_and_push
#   commit_message: string (optional, required if operation includes commit)
#   pr_title: string (optional, required if operation == create_pr)
#   pr_body: string (optional)
#   target_branch: string (optional) - defaults to main/master
#   files: array<string> (optional) - specific files to commit, defaults to all changes

# Steps
steps:
  # Step 1: Git commit (if requested)
  - name: git_commit
    type: GitCommitStep
    description: "Commit changes to current branch"
    condition: "operation == 'commit' || operation == 'commit_and_push'"
    config:
      repo: "${repo}"
      branch: "${branch}"
      message: "${commit_message}"
      files: "${files || []}"
      add_all: "${files.length == 0}"
    outputs:
      - commit_sha
      - files_committed

  # Step 2: Git push (if requested)
  - name: git_push
    type: GitPushStep
    description: "Push branch to remote"
    depends_on: ["git_commit"]
    condition: "operation == 'push' || operation == 'commit_and_push'"
    config:
      repo: "${repo}"
      branch: "${branch}"
      force: false
    outputs:
      - push_success
      - remote_ref

  # Step 3: Create PR (if requested)
  - name: create_pr
    type: GitHubPRStep
    description: "Create pull request on GitHub"
    depends_on: ["git_push"]
    condition: "operation == 'create_pr'"
    config:
      repo: "${repo}"
      head_branch: "${branch}"
      base_branch: "${target_branch || 'main'}"
      title: "${pr_title}"
      body: "${pr_body || ''}"
      draft: false
    outputs:
      - pr_number
      - pr_url

# Output mappings
outputs:
  commit_sha: "${commit_sha}"
  files_committed: "${files_committed || 0}"
  push_success: "${push_success || false}"
  pr_number: "${pr_number}"
  pr_url: "${pr_url}"
